apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: {{ .Release.Namespace }}
  labels:
    app: vote
    {{ include "voting-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.vote.replicas }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: {{ .Values.vote.image }}
          ports:
            - containerPort: {{ .Values.vote.port }}
          env:
            - name: REDIS_HOST
              value: {{ .Values.vote.env.redisHost }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.vote.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.vote.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.vote.resources | nindent 12 }}