apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: {{ .Release.Namespace }}
  labels:
    app: vote
    {{ include "voting-app.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: vote
  ports:
    - port: {{ .Values.vote.port }}
      targetPort: {{ .Values.vote.port }}
      nodePort: 30000