apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    {{ include "voting-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}