server:
  # No HTTPS for local cluster
  extraArgs:
    - --insecure

  service:
    type: NodePort
    nodePortHttp: 30002    # same as kind-config.yaml extraPortMappings

repoServer:
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 20
    failureThreshold: 10 
    timeoutSeconds: 10 
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 10      
    timeoutSeconds: 10        
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi